"""Client editor for a demo site: Decap CMS config, the /admin page, and the
Netlify build file. All generated from the same field list `_content.py` uses,
so the editor and the build can never disagree about what is editable.

Decap is a git-based editor: it has no database. The client logs in at
/admin, edits plain forms, presses Publish, and Decap commits content.json
(and any uploaded photos) to the repo. Netlify sees the commit, runs
_build.py, and the site is live again about a minute later.
"""
import os
from _deploy import REPO, BRANCH, BRIDGE

HERE = os.path.dirname(os.path.abspath(__file__))
DECAP_JS = 'https://unpkg.com/decap-cms@^3.0.0/dist/decap-cms.js'

def _y(v):
    """YAML double-quoted scalar."""
    return '"' + str(v).replace('\\', '\\\\').replace('"', '\\"') + '"'

def fields_yaml(indent=10):
    """The editor form, top to bottom. Same keys as content.json."""
    i = ' ' * indent
    f = []
    def s(name, label, widget='string', **kw):
        extra = ''.join(f', {k}: {_y(v) if isinstance(v, str) else str(v).lower()}' for k, v in kw.items())
        f.append(f'{i}- {{label: {_y(label)}, name: {name}, widget: {widget}{extra}}}')
    def group(name, label, hint, fields, summary=None):
        f.append(f'{i}- label: {_y(label)}\n{i}  name: {name}\n{i}  widget: list\n{i}  hint: {_y(hint)}')
        if summary: f.append(f'{i}  summary: {_y(summary)}')
        f.append(f'{i}  fields:')
        for name2, label2, widget2, hint2 in fields:
            h = f', hint: {_y(hint2)}' if hint2 else ''
            f.append(f'{i}    - {{label: {_y(label2)}, name: {name2}, widget: {widget2}{h}}}')

    s('brand',  'Business name (first line)', hint='Shown large in the header, e.g. Hartley')
    s('brand2', 'Business name (second line)', hint='Shown under it, e.g. Plumbing & Heating')
    s('trade',  'What you do', hint='One line, e.g. Plumber & heating engineer')
    s('town',   'Home town', hint='Where you are based')
    s('title',  'Browser tab title', hint='What Google shows as the blue link. Keep it under 60 characters.')
    s('desc',   'Google description', 'text', hint='The grey text under the blue link. One or two sentences.')
    s('phone',  'Phone number (as shown)', hint='e.g. 01632 960 118')
    s('tel',    'Phone number (for tap-to-call)', hint='Digits only with +44, e.g. +441632960118')
    s('email',  'Email address')
    s('hours',  'Opening hours', hint='e.g. Mon–Sat 8am–6pm')
    s('logo',   'Logo', 'image', required=False, hint='SVG or PNG. Leave blank to use your name as text.')
    s('hero_photo', 'Main photo (top of page)', 'image', hint='Landscape works best. Big photos are shrunk automatically.')
    s('photo1', 'Work photo 1', 'image', required=False)
    s('photo2', 'Work photo 2', 'image', required=False)
    s('eyebrow', 'Small line above the headline', hint='e.g. Gas Safe registered · No callout fee')
    s('h1',     'Headline')
    s('sub',    'Intro paragraph', 'text')
    f.append(f'{i}- {{label: "Three trust points", name: trusts, widget: list, hint: "Short, e.g. No callout charge", field: {{label: "Point", name: point, widget: string}}}}')
    s('svc_h',  'Services heading')
    s('svc_l',  'Services intro', 'text')
    group('services', 'Services & prices', 'Add, remove or reorder. The first one is featured at the top of the page.',
          [('title', 'Service', 'string', ''), ('desc', 'Description', 'text', 'One or two sentences'), ('price', 'Price', 'string', 'e.g. From £75')],
          summary='{{fields.title}} — {{fields.price}}')
    s('about_h', 'About heading')
    s('about_p', 'About paragraph', 'text')
    group('stats', 'Three numbers', 'Shown as big figures, e.g. 22 / Years on the tools',
          [('value', 'Number', 'string', ''), ('label', 'Label', 'string', '')], summary='{{fields.value}} {{fields.label}}')
    f.append(f'{i}- {{label: "Areas covered", name: areas, widget: list, hint: "Towns and districts you work in", field: {{label: "Area", name: area, widget: string}}}}')
    group('reviews', 'Reviews', 'Real reviews only. Use the customer\'s first name and surname or initial.',
          [('quote', 'Review', 'text', ''), ('name', 'Customer name', 'string', ''), ('where', 'Where they are', 'string', 'e.g. Heswall')],
          summary='{{fields.name}}')
    group('faq', 'Questions people ask', 'Three to five is plenty.',
          [('q', 'Question', 'string', ''), ('a', 'Answer', 'text', '')], summary='{{fields.q}}')
    return '\n'.join(f)

def config_yml(s):
    slug = s['slug']
    full = f"{s['brand']} {s['brand2']}"
    site_url = f'https://{slug}.launch250.co.uk'
    bridge = BRIDGE.get(slug, '')
    identity = f'https://auth.decapbridge.com/sites/{bridge}' if bridge else 'https://auth.decapbridge.com/sites/SITE-ID-NOT-SET'
    return f'''# Generated by demos/_build.py — edit _cms.py / _deploy.py, not this file.
backend:
  name: git-gateway
  repo: {REPO}
  branch: {BRANCH}
  identity_url: {identity}
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    update: "{slug}: {{{{author-name}}}} updated the site"
    uploadMedia: "{slug}: {{{{author-name}}}} added {{{{path}}}}"
    deleteMedia: "{slug}: {{{{author-name}}}} removed {{{{path}}}}"

# Handy for developers: run `npx decap-server` in the repo root and the editor
# works against your working copy with no login. Ignored in production.
local_backend: true

media_folder: "demos/{slug}/img/uploads"
public_folder: "img/uploads"

# Shrink photos in the browser before they are saved, so a 6 MB phone photo
# lands in the repo as a ~300 KB WebP. SVG logos pass through untouched.
# (_build.py does the same server-side as a safety net for anything that slips past.)
media_processing:
  enabled: true
  format:
    enabled: true
    default: webp
  quality: 82
  strip_metadata: true
  width: 2000
  height: null
site_url: {site_url}
display_url: {site_url}
logo_url: {site_url}/img/logo.svg
locale: en
editor:
  preview: false

collections:
  - name: site
    label: {_y(full)}
    description: "Everything on your website that you can change yourself. Press Publish when you are done; the site updates within a couple of minutes."
    files:
      - name: content
        label: "Text, prices & photos"
        file: "demos/{slug}/content.json"
        format: json
        fields:
{fields_yaml(10)}
'''

def admin_html(s):
    slug = s['slug']
    full = f"{s['brand']} {s['brand2']}"
    bridge = BRIDGE.get(slug, '')
    note = '' if bridge else f'''
<div id="notset" style="font:15px/1.5 system-ui,sans-serif;max-width:40rem;margin:3rem auto;padding:1.5rem;border:1px solid #e5e5e5;border-radius:12px">
  <h1 style="font-size:1.3rem;margin:0 0 .5rem">Editor not switched on yet</h1>
  <p>This site's editor has not been connected to a login service. Launch250 registers the site at DecapBridge, pastes the site id into <code>demos/_deploy.py</code> and rebuilds. Until then there is nothing to log in to.</p>
  <p style="color:#666">Developers: run <code>npx decap-server</code> from the repo root and open this page with <code>?local</code> on the end to edit the working copy without logging in.</p>
</div>'''
    # With no login service there is nothing Decap can do, so only load it when
    # a developer asks for the local proxy. Otherwise the client sees the note alone.
    loader = (f'<script src="{DECAP_JS}"></script>' if bridge else
              f'<script>if(location.search.includes("local")){{var s=document.createElement("script");s.src="{DECAP_JS}";document.body.appendChild(s);document.getElementById("notset").remove();}}</script>')
    return f'''<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Edit {full}</title>
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
</head>
<body>{note}
{loader}
</body>
</html>
'''

def netlify_toml(s):
    slug = s['slug']
    return f'''# Netlify build for {slug}.launch250.co.uk
# In the Netlify site settings set "Package directory" to demos/{slug} and leave
# "Base directory" as the repo root. Paths below are relative to the repo root.
[build]
  command = "pip install -r demos/requirements.txt && python3 demos/_build.py {slug}"
  publish = "demos/{slug}"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- demos/{slug} demos/_*.py demos/_build_css.py brand"

[build.environment]
  PYTHON_VERSION = "3.11"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"
'''

def write_all(s):
    d = os.path.join(HERE, s['slug'])
    os.makedirs(os.path.join(d, 'admin'), exist_ok=True)
    open(os.path.join(d, 'admin', 'config.yml'), 'w', encoding='utf-8').write(config_yml(s))
    open(os.path.join(d, 'admin', 'index.html'), 'w', encoding='utf-8').write(admin_html(s))
    open(os.path.join(d, 'netlify.toml'), 'w', encoding='utf-8').write(netlify_toml(s))
