CDN = "https://d8j0ntlcm91z4.cloudfront.net/user_3G5cjhlY4ceEi0osJJBdYOnenKT/hf_20260919_172621_"
def img(i): return f"url('{CDN}{i}.png')"
NONE = "none"

SITES = [
{
 "slug":"plumbing","svc_h":'Plumbing and heating, priced before we start.',"svc_l":'No callout fee, no hourly meter running. We look at the job, quote a fixed price, and that is what you pay.',"brand":"Hartley","brand2":"Plumbing & Heating","mark":"HP",
 "trade":"Plumber & heating engineer","town":"Wirral",
 "title":"Hartley Plumbing & Heating | Emergency Plumber in Wirral",
 "desc":"Gas Safe registered plumber and heating engineer covering Wirral and Chester. Emergency callouts, boiler repairs, installations. No callout fee.",
 "hero_kind":"overlay","hero_img":img("89e5e42b-d3a5-4daf-946c-fbfc961e437a"),
 "shot1":NONE,"shot2":NONE,
 "eyebrow":"Gas Safe registered · No callout fee",
 "h1":"Burst pipe? We answer the phone.",
 "sub":"Emergency plumbing and heating across Wirral and Chester. Most jobs fixed same day, fixed price agreed before we start, and a real person on the end of the line at 2am.",
 "phone":"01632 960 118","tel":"+441632960118","email":"hello@hartleyplumbing.co.uk",
 "hours":"24/7 emergency · Office Mon–Sat 8am–6pm",
 "ink":"#0d1f33","ink_soft":"#1b3a5c","accent":"#0b8fd4","accent_dark":"#0a6fa6","on_accent":"#ffffff",
 "surface":"#ffffff","wash":"#eef5fa","line":"rgba(13,31,51,.12)","muted":"#5d6b7a",
 "fd":"'Barlow Condensed', 'Arial Narrow', sans-serif","fb":"'Barlow', system-ui, sans-serif",
 "gf":"Barlow+Condensed:wght@600;700&family=Barlow:wght@400;500;600;700",
 "caps":"uppercase","track":".01em","dw":"700","radius":"6px","mark_radius":"8px",
 "star":"#f5a623","foot":"#08192a",
 "overlay":"rgba(8,25,42,.93)","overlay_mid":"rgba(8,25,42,.72)",
 "pat":["rgba(11,143,212,.18)","#0d1f33","#0b8fd4"],
 "trusts":["Gas Safe registered","No callout charge","Fixed price, agreed first"],
 "services":[
  ("Emergency callouts","Burst pipes, leaks, no heating, no hot water. We aim to be with you within the hour, day or night.","From £75"),
  ("Boiler repair & servicing","Gas Safe repairs on all major brands, plus annual services and landlord safety certificates.","From £90"),
  ("Boiler installation","New combi and system boilers supplied and fitted, with up to 10 years manufacturer warranty.","From £1,850"),
  ("Bathroom installation","Full bathroom fits, from a straight swap to strip-out and redesign. Tiling and electrics handled.","From £2,400"),
  ("Leaks & drainage","Leak detection, blocked drains, overflow and soil pipe work. We find it before we tear anything out.","From £85"),
  ("Landlord certificates","CP12 gas safety certificates for landlords and letting agents. Same-week appointments.","£75"),
 ],
 "about_h":"Twenty-two years under sinks across the Wirral.",
 "about_p":"Hartley Plumbing is Dean Hartley and two engineers — not a call centre that subcontracts your job to whoever is nearest. We are Gas Safe registered, fully insured, and we price the work before we pick up a spanner. If we cannot fix it today, we will tell you straight and book you in for when we can.",
 "stats":[("22","Years on the tools"),("1,800+","Jobs completed"),("4.9","Average rating")],
 "areas":["Wirral","Birkenhead","Heswall","West Kirby","Bebington","Neston","Chester","Ellesmere Port"],
 "reviews":[
  ("Came out at half eleven at night when our heating packed in with a newborn in the house. Fixed it in forty minutes and charged exactly what he quoted on the phone.","Claire Dawson","Heswall"),
  ("Had three quotes for a new combi. Dean was not the cheapest but he was the only one who actually explained why the others were wrong. Two years on, faultless.","Martin Rowe","Bebington"),
  ("Full bathroom rip out and refit in six days. Tidy, on time, and they hoovered up every night before leaving. Cannot fault them.","Priya Shah","West Kirby"),
 ],
 "faq":[
  ("Do you charge a callout fee?","No. We quote a fixed price for the job before we start, and that is what you pay. If you decide not to go ahead, you owe us nothing."),
  ("How fast can you get to an emergency?","For genuine emergencies in the Wirral area we aim to be with you inside an hour, 24 hours a day. Ring us rather than using the form and you will speak to an engineer."),
  ("Are you Gas Safe registered?","Yes, and we will show you the card before we touch anything gas. Never let anyone work on your gas appliances without it."),
 ],
},
{
 "slug":"electrical","svc_h":'Electrical work, certified and quoted up front.',"svc_l":'Every job leaves with the right certificate and a price agreed in writing beforehand.',"brand":"Marsden","brand2":"Electrical","mark":"ME",
 "trade":"Electrician","town":"Chester",
 "title":"Marsden Electrical | NICEIC Electrician in Chester",
 "desc":"NICEIC approved electrician in Chester. Rewires, consumer units, EV charger installation, EICR reports and emergency callouts. Free written quotes.",
 "hero_kind":"overlay","hero_img":img("19abc826-193c-4786-a49e-a7ed69365092"),
 "shot1":NONE,"shot2":NONE,
 "eyebrow":"NICEIC approved · Part P registered",
 "h1":"Electrics done properly. First time.",
 "sub":"Domestic and commercial electrical work across Chester and Cheshire. Rewires, fuse boards, EV chargers and EICR reports — all certified, all guaranteed, all quoted in writing.",
 "phone":"01632 960 244","tel":"+441632960244","email":"office@marsdenelectrical.co.uk",
 "hours":"Mon–Fri 7.30am–6pm · Emergency 24/7",
 "ink":"#121418","ink_soft":"#1e2128","accent":"#ffcc00","accent_dark":"#8a6d00","on_accent":"#121418",
 "surface":"#ffffff","wash":"#f6f6f4","line":"rgba(18,20,24,.12)","muted":"#5f636b",
 "fd":"'Oswald', 'Arial Narrow', sans-serif","fb":"'Inter', system-ui, sans-serif",
 "gf":"Oswald:wght@500;600;700&family=Inter:wght@400;500;600;700",
 "caps":"uppercase","track":".015em","dw":"600","radius":"4px","mark_radius":"6px",
 "star":"#ffcc00","foot":"#0b0d10",
 "overlay":"rgba(10,12,15,.94)","overlay_mid":"rgba(10,12,15,.7)",
 "pat":["rgba(255,204,0,.16)","#121418","#3a3d44"],
 "trusts":["NICEIC approved contractor","Certificates with every job","Free written quotes"],
 "services":[
  ("Full & partial rewires","Whole-house rewires with minimal mess, plus partial rewires where only part of the property needs bringing up to standard.","From £2,900"),
  ("Consumer unit upgrades","Modern 18th edition boards with RCBO protection. Old rewireable fuse boxes swapped in a day.","From £480"),
  ("EV charger installation","OZEV approved installer. 7kW home chargers fitted and commissioned, usually in half a day.","From £850"),
  ("EICR & landlord reports","Electrical Installation Condition Reports for homeowners, landlords and letting agents. Digital certificate within 24 hours.","From £150"),
  ("Lighting design & fitting","Downlights, garden lighting, under-cabinet and feature lighting. Designed properly, not just dotted about.","From £220"),
  ("Fault finding & repairs","Tripping circuits, dead sockets, flickering lights. We find the actual cause rather than guessing.","From £85"),
 ],
 "about_h":"Certified work, plain English, no surprises.",
 "about_p":"Ryan Marsden has been an electrician for eighteen years, the last nine running Marsden Electrical. Every job leaves with the right certificate, notified to building control where it needs to be. We turn up when we say, we clean up after ourselves, and we will explain what we are doing without the jargon.",
 "stats":[("18","Years qualified"),("2,400+","Jobs certified"),("24hr","EICR turnaround")],
 "areas":["Chester","Ellesmere Port","Neston","Tarporley","Frodsham","Mold","Wrexham","Northwich"],
 "reviews":[
  ("Rewired our whole 1930s semi while we lived in it. Dust sheets everywhere, hoovered daily, and finished two days early. The certificate landed in my inbox the same afternoon.","Tom Ellison","Chester"),
  ("Needed an EICR at short notice for a rental. Booked Tuesday, done Thursday, report that evening. Letting agent said it was the clearest one they had seen.","Sandra Pike","Ellesmere Port"),
  ("Fitted our EV charger and sorted a dodgy kitchen circuit he spotted while he was there. Charged me for half an hour extra, not a whole new job.","Dan Okafor","Frodsham"),
 ],
 "faq":[
  ("Will I get a certificate?","Always. Every notifiable job is certified and registered with building control through NICEIC, and you get the paperwork by email the same week."),
  ("Can you install an EV charger with a grant?","We are an OZEV approved installer, so if you qualify for a grant we handle the application as part of the job."),
  ("Do you do emergency work?","Yes, 24/7 for genuine electrical emergencies — burning smells, sparking, total power loss. Ring rather than email."),
 ],
},
{
 "slug":"joinery","svc_h":'What we make.',"svc_l":'Everything is built to your measurements in our own workshop. The prices below are honest starting points for a typical room.',"brand":"Northgate","brand2":"Joinery","mark":"NJ",
 "trade":"Joiner & kitchen fitter","town":"Wirral",
 "title":"Northgate Joinery | Bespoke Fitted Furniture & Kitchens, Wirral",
 "desc":"Bespoke joinery on the Wirral. Handmade fitted wardrobes, alcove units, kitchens and staircases, designed and made for your space. Free design visit.",
 "hero_kind":"type","hero_img":NONE,
 "shot1":NONE,"shot2":NONE,
 "eyebrow":"Bespoke joinery since 2004",
 "h1":"Made for your house. Not off a shelf.",
 "sub":"Handmade fitted wardrobes, alcove units, kitchens and staircases — designed around the awkward corners of your actual home, built in our Wirral workshop, fitted by the person who made them.",
 "phone":"01632 960 377","tel":"+441632960377","email":"dave@northgatejoinery.co.uk",
 "hours":"Workshop Mon–Fri 8am–5pm · Sat by appointment",
 "ink":"#2b2118","ink_soft":"#3d2f22","accent":"#a8722f","accent_dark":"#7d5220","on_accent":"#ffffff",
 "surface":"#ffffff","wash":"#f6f1e8","line":"rgba(43,33,24,.14)","muted":"#6d6055",
 "fd":"'Fraunces', Georgia, serif","fb":"'Inter', system-ui, sans-serif",
 "gf":"Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&family=Inter:wght@400;500;600",
 "caps":"none","track":"-.02em","dw":"600","radius":"10px","mark_radius":"10px",
 "star":"#a8722f","foot":"#241a12",
 "overlay":"rgba(36,26,18,.92)","overlay_mid":"rgba(36,26,18,.68)",
 "pat":["rgba(168,114,47,.2)","#3d2f22","#a8722f"],
 "trusts":["Made in our own workshop","Free design visit","10 year guarantee"],
 "services":[
  ("Fitted wardrobes","Floor to ceiling, wall to wall, around the chimney breast and under the slope. Shaker, flat panel or traditional.","From £1,400"),
  ("Alcove units & shelving","Those two awkward gaps either side of the fireplace, turned into the best storage in the house.","From £850"),
  ("Handmade kitchens","Solid timber frames, painted in any colour, with the drawers where you actually want them.","From £6,500"),
  ("Staircases & balustrades","New oak staircases, or re-covering and re-spindling a tired existing one. Glass, timber or steel.","From £2,200"),
  ("Home offices & media walls","Built-in desks, cable management that actually works, and shelving sized to your books not a catalogue.","From £1,100"),
  ("Doors, skirting & architrave","Period-correct mouldings matched to your house, hung and finished properly.","From £180"),
 ],
 "about_h":"One joiner. Twenty years. Every job start to finish.",
 "about_p":"Dave Kilbride served his time as a bench joiner and has been making fitted furniture on the Wirral since 2004. There is no sales team — the person who measures your room is the person who makes the piece and the person who fits it. That is why nothing ever gets lost in translation, and why the scribe lines actually fit your wonky Victorian walls.",
 "stats":[("20","Years at the bench"),("600+","Pieces made"),("10yr","Guarantee")],
 "areas":["Wirral","Heswall","West Kirby","Hoylake","Caldy","Bebington","Chester","Neston"],
 "reviews":[
  ("Our bedroom has a bay, a chimney breast and a sloping ceiling. Three companies said it was not possible. Dave measured it, drew it, and made it fit perfectly.","Rachel Moore","Caldy"),
  ("The alcove units look like they have been there since the house was built in 1904. That is exactly what we asked for and exactly what we got.","James Whitfield","Hoylake"),
  ("Handmade kitchen, painted in a colour we picked. Six weeks from design to finished. The drawers are still silent two years later.","Anna Lindqvist","West Kirby"),
 ],
 "faq":[
  ("How long does a fitted wardrobe take?","Usually four to six weeks from design sign-off to fitting. Most of that is workshop time — the fit itself is normally one or two days."),
  ("Can you match existing woodwork?","Yes. We profile existing skirting and architrave and cut matching mouldings, which is why the work sits right in period houses."),
  ("Is the design visit really free?","Completely. We come out, measure, talk through options and send a fixed written quote. No deposit until you are happy with the drawings."),
 ],
},
{
 "slug":"landscaping","svc_h":'What we build.',"svc_l":'Design and build under one roof, so nobody can blame anybody else. Fixed price, fixed dates, staged payments.',"brand":"Greenacre","brand2":"Landscapes","mark":"GL",
 "trade":"Landscaper & garden designer","town":"Cheshire",
 "title":"Greenacre Landscapes | Garden Design & Landscaping, Cheshire",
 "desc":"Garden design and landscaping across Cheshire. Patios, driveways, fencing, turfing and full garden transformations. Free site visit and 3D design.",
 "hero_kind":"overlay","hero_img":img("3fa514c2-c472-4afd-a203-11ab58c6a8a5"),
 "shot1":NONE,"shot2":NONE,
 "eyebrow":"Design & build · Fully insured",
 "h1":"A garden you actually go outside for.",
 "sub":"Design-and-build landscaping across Cheshire. Patios, planting, fencing, lawns and full transformations — drawn up properly, priced fixed, and finished when we said we would finish.",
 "phone":"01632 960 512","tel":"+441632960512","email":"studio@greenacrelandscapes.co.uk",
 "hours":"Mon–Fri 7.30am–5.30pm · Sat 9am–1pm",
 "ink":"#14301f","ink_soft":"#1e4530","accent":"#5aa845","accent_dark":"#3d7a2e","on_accent":"#ffffff",
 "surface":"#ffffff","wash":"#eef4ea","line":"rgba(20,48,31,.13)","muted":"#5a6b5e",
 "fd":"'Outfit', system-ui, sans-serif","fb":"'Inter', system-ui, sans-serif",
 "gf":"Outfit:wght@500;600;700&family=Inter:wght@400;500;600",
 "caps":"none","track":"-.025em","dw":"700","radius":"12px","mark_radius":"12px",
 "star":"#5aa845","foot":"#0f2417",
 "overlay":"rgba(15,36,23,.92)","overlay_mid":"rgba(15,36,23,.62)",
 "pat":["rgba(90,168,69,.2)","#1e4530","#5aa845"],
 "trusts":["Free 3D design","Fixed price, fixed dates","5 year workmanship guarantee"],
 "services":[
  ("Patios & paving","Indian sandstone, porcelain and block paving, laid on a full mortar bed so it is still flat in ten years.","From £2,800"),
  ("Garden design","Measured survey and a 3D visual so you can see it before you commit. Free if we build it.","From £450"),
  ("Fencing & screening","Close board, feather edge, slatted screens and sleeper walls. Concrete posts as standard.","From £65/m"),
  ("Turfing & lawn care","New lawns laid on properly prepared ground, plus scarifying, feeding and seasonal maintenance.","From £14/m²"),
  ("Driveways","Block paved and resin bound driveways with correct drainage and SUDS compliance.","From £4,200"),
  ("Planting schemes","Borders planned for year-round interest and your actual soil, not a garden centre trolley dash.","From £900"),
 ],
 "about_h":"We design it, we build it, we stand behind it.",
 "about_p":"Greenacre is a five-person team working across Cheshire and the Wirral. We do not subcontract — the people who draw your garden are the people who build it. Every job gets a fixed price, a start date and an end date in writing, and we do not ask for money up front. You pay in stages as the work goes in.",
 "stats":[("12","Years landscaping"),("340+","Gardens built"),("5yr","Guarantee")],
 "areas":["Chester","Tarporley","Northwich","Knutsford","Wilmslow","Nantwich","Frodsham","Wirral"],
 "reviews":[
  ("They turned a sloping, waterlogged mess into three usable terraces. The drainage work alone was worth it — no standing water through two winters since.","Helen Braithwaite","Tarporley"),
  ("The 3D design sold it to my husband. It looked exactly like the drawing when they finished, which apparently is not normal.","Gemma Price","Knutsford"),
  ("Fixed price, fixed dates, and they hit both. Cleared up every single evening. The neighbours have booked them too.","Alan Forsyth","Chester"),
 ],
 "faq":[
  ("Do you charge for the design?","A measured survey and 3D design is £450, and we take it straight off the build cost if you go ahead with us. If you do not, the drawings are yours to keep."),
  ("When is the best time to start?","We landscape all year. Hard landscaping — patios, walls, fencing — is fine through winter. Turf and planting are best spring or autumn."),
  ("Do you need paying up front?","No. You pay in stages as work is completed, with nothing due until the first stage is finished."),
 ],
},
{
 "slug":"barbers","svc_h":'The menu.',"svc_l":'No hidden extras and no upselling. Walk in, sit down, and pay what is on the board.',"brand":"The Corner","brand2":"Barbers","mark":"CB",
 "trade":"Barbershop","town":"Liverpool",
 "title":"The Corner Barbers | Traditional Barbershop, Liverpool",
 "desc":"Traditional barbershop in Liverpool. Skin fades, beard trims, hot towel shaves and kids cuts. Walk in or book online. Open six days.",
 "hero_kind":"overlay","hero_img":img("db95aa74-8fb3-4ab5-9fba-40f7e6c16401"),
 "shot1":NONE,"shot2":NONE,
 "eyebrow":"Est. 2016 · Walk-ins welcome",
 "h1":"Proper barbering. No appointment needed.",
 "sub":"Skin fades, scissor work, beard sculpting and hot towel shaves in the heart of Liverpool. Six chairs, six days a week, and a brew while you wait.",
 "phone":"01632 960 733","tel":"+441632960733","email":"bookings@thecornerbarbers.co.uk",
 "hours":"Mon–Fri 9am–7pm · Sat 8am–6pm · Sun closed",
 "ink":"#101010","ink_soft":"#1c1c1c","accent":"#c8a54b","accent_dark":"#8f7327","on_accent":"#101010",
 "surface":"#ffffff","wash":"#f4f2ed","line":"rgba(16,16,16,.13)","muted":"#63605a",
 "fd":"'Bebas Neue', Impact, sans-serif","fb":"'Inter', system-ui, sans-serif",
 "gf":"Bebas+Neue&family=Inter:wght@400;500;600;700",
 "caps":"none","track":".02em","dw":"400","radius":"2px","mark_radius":"4px",
 "star":"#c8a54b","foot":"#0a0a0a",
 "overlay":"rgba(8,8,8,.9)","overlay_mid":"rgba(8,8,8,.6)",
 "pat":["rgba(200,165,75,.2)","#1c1c1c","#c8a54b"],
 "trusts":["Walk-ins always welcome","Six barbers, no waiting about","Card & cash"],
 "services":[
  ("Skin fade","Clipper work taken down to the skin and blended properly. The cut we are known for.","£18"),
  ("Cut & style","Scissor cut, washed, dried and styled with product that suits your hair, not ours.","£16"),
  ("Beard trim & shape","Lined up with a razor, balanced to your face, finished with oil and a hot towel.","£12"),
  ("Hot towel wet shave","The full traditional service. Hot towels, badger brush, straight razor, cold finish.","£25"),
  ("Cut & beard combo","Full haircut and beard service together, and you save a fiver doing it.","£26"),
  ("Under 12s","Kids cuts, no fuss, booster seat for the little ones and a lolly at the end.","£11"),
 ],
 "about_h":"Six chairs on the corner since 2016.",
 "about_p":"We opened The Corner because Liverpool had plenty of places to get your hair cut and not many to get it cut properly. Every barber here has served an apprenticeship. We take walk-ins all day, we will tell you honestly if what you have asked for will not suit you, and nobody gets rushed out of the chair.",
 "stats":[("6","Barbers on the floor"),("40k+","Cuts since opening"),("4.9","From 480 reviews")],
 "areas":["Liverpool City Centre","Baltic Triangle","Georgian Quarter","Toxteth","Aigburth","Bootle","Wavertree","Anfield"],
 "reviews":[
  ("Been going three years and never had a bad cut, whoever is on. That consistency is rarer than it should be.","Michael Doran","Liverpool"),
  ("Walked in on a Saturday morning expecting an hour wait. Sat down in ten minutes, out in forty with the best fade I have had.","Jordan Achebe","Aigburth"),
  ("Took my lad for his first proper haircut. They were brilliant with him, made a fuss of him, and he has asked to go back since.","Steve Whelan","Bootle"),
 ],
 "faq":[
  ("Do I need to book?","No — we take walk-ins every day and that is most of our trade. You can book online if you want a specific barber or a wet shave, which takes longer."),
  ("How long will I wait?","Usually under fifteen minutes. Saturday mornings and late afternoons are busiest; mid-morning midweek you will walk straight in."),
  ("Do you cut children's hair?","Every day. Under 12s are £11 and we have a booster seat. First haircuts are a bit of an occasion here."),
 ],
},
{
 "slug":"doggrooming","svc_h":'Grooming services.',"svc_l":'Prices vary a little with size and coat condition. Send a photo and we will confirm before we book you in.',"brand":"Muddy Paws","brand2":"Mobile Grooming","mark":"MP",
 "trade":"Mobile dog groomer","town":"Cheshire",
 "title":"Muddy Paws | Mobile Dog Grooming in Cheshire — We Come to You",
 "desc":"Fully equipped mobile dog grooming van covering Cheshire. One dog at a time, no cages, no waiting. Book your regular slot online.",
 "hero_kind":"type","hero_img":NONE,
 "shot1":NONE,"shot2":NONE,
 "eyebrow":"We come to your door",
 "h1":"Grooming without the stressful day out.",
 "sub":"A fully equipped grooming salon that parks on your driveway. One dog at a time, no cages, no waiting around in kennels — just your dog, your groomer, and about ninety minutes.",
 "phone":"01632 960 866","tel":"+441632960866","email":"book@muddypawsmobile.co.uk",
 "hours":"Mon–Sat 8am–6pm · Sunday by arrangement",
 "ink":"#123b3b","ink_soft":"#1a5252","accent":"#ff7a59","accent_dark":"#c9502f","on_accent":"#ffffff",
 "surface":"#ffffff","wash":"#e9f4f3","line":"rgba(18,59,59,.13)","muted":"#557070",
 "fd":"'Quicksand', system-ui, sans-serif","fb":"'Nunito', system-ui, sans-serif",
 "gf":"Quicksand:wght@600;700&family=Nunito:wght@400;500;600;700",
 "caps":"none","track":"-.015em","dw":"700","radius":"16px","mark_radius":"14px",
 "star":"#ff7a59","foot":"#0d2e2e",
 "overlay":"rgba(13,46,46,.92)","overlay_mid":"rgba(13,46,46,.64)",
 "pat":["rgba(255,122,89,.22)","#1a5252","#ff7a59"],
 "trusts":["City & Guilds qualified","One dog at a time","Fully insured"],
 "services":[
  ("Full groom","Bath, blow dry, full clip or hand strip, nails, ears and a finishing spritz. The works.","From £45"),
  ("Bath & tidy","Wash, dry, nail trim and a tidy of face, feet and rear. Perfect between full grooms.","From £28"),
  ("Puppy's first groom","A gentle, short introduction session so grooming never becomes something to dread.","£22"),
  ("De-shedding treatment","Specialist bath and rake for double-coated breeds. Dramatically less hair on your sofa.","From £38"),
  ("Hand stripping","Correct coat care for terriers and wire-haired breeds, done by hand the way it should be.","From £55"),
  ("Nails, ears & anal glands","Quick welfare visits without a full groom. Ten minutes on the driveway.","£15"),
 ],
 "about_h":"Kirsty, a van, and a lot of very relaxed dogs.",
 "about_p":"Muddy Paws is Kirsty Bell, City & Guilds qualified with nine years in salons before going mobile. The van has hot water, a hydraulic table, proper lighting and heating. Your dog is never caged and never waits — the session starts when Kirsty arrives and your dog goes straight back inside afterwards. Nervous and elderly dogs are a speciality.",
 "stats":[("9","Years grooming"),("500+","Regular dogs"),("1:1","Never more than one dog")],
 "areas":["Chester","Tarporley","Frodsham","Helsby","Northwich","Kelsall","Tattenhall","Malpas"],
 "reviews":[
  ("Our rescue lurcher panics in salons. Kirsty did three short sessions to build him up and now he trots to the van on his own.","Nicola Grant","Tarporley"),
  ("The convenience is unreal. She grooms him on the drive while I work and I do not lose half a Saturday sat in a waiting room.","Paul Ridley","Chester"),
  ("Our old collie is fourteen and arthritic. Kirsty works around him, takes breaks, never rushes. That care is worth every penny.","Fiona Mackay","Helsby"),
 ],
 "faq":[
  ("Do you need my water or electricity?","No. The van is completely self-contained with its own water, heating and power, so all we need is somewhere legal to park near your door."),
  ("How long does a groom take?","A full groom is usually 90 minutes to two hours depending on coat and size. You will get a text when we are fifteen minutes away."),
  ("What if my dog is nervous?","Tell us when you book. Nervous and elderly dogs are what we are best at — we will take it at their pace, over several short visits if needed."),
 ],
},
]
